# Generated by Django 5.2.6 on 2025-09-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('resource_type', models.CharField(choices=[('BOOK', 'Book'), ('PAPER', 'Paper'), ('LINK', 'Link'), ('NOTE', 'Note'), ('PDF', 'PDF')], max_length=5)),
                ('authors', models.CharField(blank=True, max_length=500, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('content', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.academicarea')),
            ],
        ),
        migrations.CreateModel(
            name='CanvasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_items', to='api.academicarea')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_placements', to='api.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='api.academicarea')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='api.resource')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_connections', to='api.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.academicarea')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.resource')),
            ],
        ),
    ]
