# Generated by Django 5.2.6 on 2025-09-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicarea',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
